sudo: false
language: python
dist: xenial

jobs:
  include:
    - stage: static-tests
      name: fmt
      python: "3.7"
      before_script:
        - pip install black==19.10b0 isort==4.3.21
      script:
        - black --version
        - echo -n "isort " && isort --version-number
        - black -l 100 --exclude '/(\..*)/' --diff --check hapic tests example
        - isort -df -c **/*.py
    - stage: static-tests
      name: flake8
      python: "3.7"
      before_script:
        - pip install flake8
      script:
        - flake8 --version
        - flake8
    - stage: tests
      name: tests python3.5
      python:
        - "3.5"
      before_script:
        - python setup.py develop
        - pip install -e ."[test_marshmallow]"
      script:
        - pytest --cov=hapic tests -vvvvv
    - stage: tests
      name: tests python3.6
      python:
        - "3.6"
      before_script:
        - python setup.py develop
        - pip install -e ."[test]"
      script:
        - pytest --cov=hapic tests -vvvvv
    - stage: tests
      name: tests python3.7
      python:
        - "3.7"
      before_script:
        - python setup.py develop
        - pip install -e ."[test]"
      script:
        - pytest --cov=hapic tests -vvvvv
    - stage: tests
      name: tests python3.8
      python:
        - "3.8"
      before_script:
        - python setup.py develop
        - pip install -e ."[test]"
      script:
        - pytest --cov=hapic tests -vvvvv
      after_success:
        - coveralls
